### ISSUE TITLE
Service Annotations in pulsar admin console incorrectly scoped

### ISSUE THREAD

**Issue by robparrott** [datastax/pulsar-helm-chart#129]
At this line:

* https://github.com/datastax/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/templates/admin-console/pulsar-admin-console-service.yaml#L32

The helm variables name for service annotations is `.Values.pulsarAdminConsole.annotations` but should be scoped to the service, consistent with other components, as `.Values.pulsarAdminConsole.service.annotations`

Workaround is to change your values.yaml to match, but it is then inconsistent with standards and the other components of the chart.

**Comment by michaeljmarshall** [comment]
@robparrott - thanks for identifying this issue. You're right that this is inconsistent. Based on looking at our current `values.yaml` file and our available values, I believe the `.Values.pulsarAdminConsole.annotations` field is meant for the Admin Console deployment. Also, there is already a `.Values.pulsarAdminConsole.service.annotations` field defined, it just wasn't used. I think we should use both for now, and then in the next major version bump, we can remove `.Values.pulsarAdminConsole.annotations` from the service's annotation config. Please see https://github.com/datastax/pulsar-helm-chart/pull/143, for more information.
