### ISSUE TITLE
PulsarSQL ingress port is wrong

### ISSUE THREAD

**Issue by robparrott** [datastax/pulsar-helm-chart#132]
INgress for pulsarSQL points to port 8080 on the service at this line (hardcoded):

* https://github.com/datastax/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/templates/pulsarSql/ingress.yaml#L42

But the default values is set for port 8090, thus breaking deployments.

**Comment by michaeljmarshall** [comment]
@robparrott - thanks for raising this issue. I just opened a PR to resolve the issue.
