### ISSUE TITLE
Unable to specify loadBalancerIP on Services

### ISSUE THREAD

**Issue by liamgib** [datastax/pulsar-helm-chart#139]
I'd like to set an internal static IP to a service with type LoadBalancer, but there is no configuration available to define this. 
Could we get a service.loadBalancerIP option for pulsar services so this could be set via helm?

**Comment by michaeljmarshall** [comment]
@liamgib - thanks for identifying this issue. #141 should resolve the issue. Please let me know if there is a service you think I missed.
