### ISSUE TITLE
Update Ingress API Version

### ISSUE THREAD

**Issue by michaeljmarshall** [datastax/pulsar-helm-chart#140]
Sample warning when using the Ingress for PulsarSQL:

> W0128 16:06:08.502415   22507 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by michaeljmarshall** [comment]
Here is the relevant documentation https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122. Since we still support 1.19, we'll need to branch based on the k8s version.

**Comment by lhotari** [comment]
the change in Apache Pulsar Helm chart: https://github.com/datastax/pulsar-helm-chart/issues/140 . It's more than just changing the apiVersion. it looks like the schema has changed slightly.

**Comment by lhotari** [comment]
resolved by #154
