### ISSUE TITLE
Missing charts

### ISSUE THREAD

**Issue by HankHannah** [datastax/pulsar-helm-chart#152]
1. Using current master branch helmcharts
2. Download dev-values.yaml
3. helm install pulsar-hank  -n hank-test -f dev-values.yaml ./pulsar/
Out: Error: found in Chart.yaml, but missing in charts/ directory: kube-prometheus-stack, cert-manager, keycloak

**Comment by eolivelli** [comment]
You should run helm dependency update

**Comment by eolivelli** [comment]
You can follow the instructions on the README
