### ISSUE TITLE
Support existing Keycloak instance

### ISSUE THREAD

**Issue by nealf** [datastax/pulsar-helm-chart#181]
Thanks for the OIDC plugin and including a setup for Keycloak in this helm chart! 

For those of us who already have existing Keycloak instances, it would be great to be able to leverage those by configuring the Keycloak component to point to our existing instance rather than deploying a new one.

**Comment by michaeljmarshall** [comment]
@nealf - thanks for creating this issue. I agree that we should implement this feature. I am not sure when but I plan to add this feature soon. The final solution will allow for any OIDC Identity Provider, not just the an existing Keycloak instance.
