### ISSUE TITLE
Pulsar-hearbeat init container is connecting with port 8080 on broker

### ISSUE THREAD

**Issue by sssd-dev** [datastax/pulsar-helm-chart#185]
After enabling tls on broker and disabling port 8080, pulsar hearbeat init container is still trying to connect to port 8080.

https://github.com/datastax/pulsar-helm-chart/blob/pulsar-2.1.3/helm-chart-sources/pulsar/templates/pulsar-heartbeat/pulsar-heartbeat-deployment.yaml#L71

curl command should be trying to connect to port 8443 after enabling tls on broker by hitting `https` endpoint instead of currently configured `http`.

**Comment by michaeljmarshall** [comment]
Thanks for creating this issue @sssd-dev. I agree that the heartbeat should use the https port when `enableTls: true`.
