### ISSUE TITLE
Missing logs button on Source

### ISSUE THREAD

**Issue by liamgib** [datastax/pulsar-helm-chart#253]
Hello! 

We recently updated to the latest version of the chart, and strangely enough, the logs button on the source page has disappeared. 
It was really helpful to debug/view errors when sources stopped working. 

Was this an upstream change? Unsure if it is now a configuration option, but would be nice to have again.
![image](https://user-images.githubusercontent.com/40730821/182053557-ac2a19ca-803d-4fc5-ae16-8cdb2839360b.png)

**Comment by cdbartholomew** [comment]
This is due to change in the admin console. CC/ @mfortman11

**Comment by liamgib** [comment]
Hi @cdbartholomew / @mfortman11 

Any update on this? In which release was this changed so we can revert?
