### ISSUE TITLE
Convert load balancer from network load balancer to application load balancer to add security groups in AWS.

### ISSUE THREAD

**Issue by olsenpabu** [datastax/pulsar-helm-chart#292]
Is it possible to convert load balancer from network load balancer to application load balancer to add security groups in AWS? this is for the pulsar proxy, grafana and admin console.

**Comment by michaeljmarshall** [comment]
The pulsar protocol is built on layer 4, so I don't believe an ALB will work because it uses layer 7 for routing. The pulsar admin end point and the other endpoints you referenced are HTTP though, so it could be possible to expose them via an ALB.

**Comment by olsenpabu** [comment]
Hi @michaeljmarshall,

Noted on this.

Thank you for your response!
