### ISSUE TITLE
Pulsar Admin Console does not work

### ISSUE THREAD

**Issue by eolivelli** [datastax/pulsar-helm-chart#7]
I have just installed this helm-chart on a brand new k8s cluster
the admin-console seems to work, but it reality it doesn't

Chrome console is full of errors like this one
xhr.js:175 GET http://localhost:8888/api/v1/pulsar/tenants 502 (Bad Gateway)
and other timeout errors

**Comment by cdbartholomew** [comment]
Are all the pods up? What does `kubectl get pods` show?

**Comment by eolivelli** [comment]
> (ctool-env) enrico.olivelli@eolivelli-rmbp16 pulsar % kubectl get pods
> NAME                                                   READY   STATUS             RESTARTS   AGE
> prometheus-pulsar-kube-prometheus-sta-prometheus-0     2/2     Running            1          3h42m
> pulsar-adminconsole-9f466fc7c-7dtsp                    2/2     Running            0          3h42m
> pulsar-autorecovery-859bd5dfc8-2gjpx                   1/1     Running            4          3h42m
> pulsar-bastion-7489594b85-fxjz7                        1/1     Running            0          3h42m
> pulsar-bookkeeper-0                                    1/1     Running            0          3h42m
> pulsar-bookkeeper-1                                    1/1     Running            0          3h36m
> pulsar-bookkeeper-2                                    1/1     Running            0          3h35m
> pulsar-broker-5544654bc5-7v2fq                         1/1     Running            0          3h42m
> pulsar-broker-5544654bc5-cprs4                         1/1     Running            0          3h42m
> pulsar-broker-5544654bc5-skmhw                         1/1     Running            0          3h42m
> pulsar-cert-manager-54bd6f7657-wjj84                   1/1     Running            0          3h42m
> pulsar-cert-manager-cainjector-6f6cd75658-kzpwt        1/1     Running            0          3h42m
> pulsar-cert-manager-webhook-8f4ddcd65-pwgqs            1/1     Running            0          3h42m
> pulsar-function-0                                      2/2     Running            0          3h42m
> pulsar-grafana-856bfd8897-vs4cd                        2/2     Running            0          3h42m
> pulsar-kube-prometheus-sta-admission-patch-4zlkn       0/1     Completed          0          3h42m
> pulsar-kube-prometheus-sta-operator-744cdf65b8-n9bwp   1/1     Running            0          3h42m
> pulsar-kube-state-metrics-74f49d8b4c-sbnnd             1/1     Running            0          3h42m
> pulsar-prometheus-node-exporter-4nd5f                  1/1     Running            0          3h42m
> pulsar-prometheus-node-exporter-7vxbk                  1/1     Running            0          3h42m
> pulsar-prometheus-node-exporter-bq677                  1/1     Running            0          3h42m
> pulsar-prometheus-node-exporter-rrfcn                  1/1     Running            0          3h42m
> pulsar-proxy-7dfc7b69c4-sqmmf                          2/3     ImagePullBackOff   0          3h42m
> pulsar-pulsarheartbeat-5b9f666d8-vhtdt                 1/1     Running            0          3h42m
> pulsar-zookeeper-0                                     1/1     Running            0          3h42m
> pulsar-zookeeper-metadata-wmk87                        0/1     Completed          0          3h42m
