### ISSUE TITLE
PulsarSQL worker misconfigured and will not start.

### ISSUE THREAD

**Issue by robparrott** [datastax/pulsar-helm-chart#86]
The pulsar SQL worker pod fails to start due to the erroneous configuration value `discovery-server.enabled=true` in `config.properties`. Per this discussion: 

 https://groups.google.com/g/presto-users/c/AetYYMvfsiA?pli=1

This is no longer a valid config option. Removing this configuration fixes the start up problem.

**Comment by michaeljmarshall** [comment]
@robparrott - thanks for sharing a source there. I observed the same issue when testing Pulsar SQL yesterday. I'll remove that config from the configmap tomorrow.
